# # Complex Examples
#md # [![](https://mybinder.org/badge_logo.svg)](@__BINDER_ROOT_URL__/notebooks/complexexamples.ipynb)
#md # [![](https://img.shields.io/badge/show-nbviewer-579ACA.svg)](@__NBVIEWER_ROOT_URL__/notebooks/complexexamples.ipynb)

# To begin using JuliaPackageDemo.jl we first need to load in the package with the `using` syntax. We will also load in DelimitedFiles.jl so we can import some data.

using JuliaPackageDemo
using DelimitedFiles

# Let's load in some data.
inputdataraw = readdlm("assets/data.csv", ',')
inputdata = vcat(inputdataraw...) 

# Now we can use it as the input arguments for [`coolfunction1`](@ref).
## get function values at time points
data = coolfunction1.(inputdata)

# For more information on [`coolfunction1`](@ref) please see the [API](@ref) section. Now we can try something similar with [`coolfunction2`](@ref):

## get function values at time points
data = coolfunction2.(inputdata)

# Finally, let's write that data generated by [`coolfunction2`](@ref) to a file.
open("assets/outputdata.csv", "w") do io
    writedlm(io, data)
end

# For more simple examples, see [Simple Examples](@ref) section.